using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace GxMcp.Worker.Helpers
{
    /// <summary>
    /// Finds blocks of commented-OUT CODE (dead code) in GeneXus source — linter rule GX015.
    /// Pure string logic, no SDK: LinterService orchestrates, this detects, tests pin it.
    ///
    /// Two hazards shape everything here, and both were measured against a real KB before
    /// freezing this design:
    ///
    /// 1. GENERATED CODE MUST NOT BE FLAGGED. WorkWithPlus (DVelop) wraps its generated
    ///    regions in paired markers — verified live on MatikaPayment_2702 (18 pairs in one
    ///    WebPanel's Events):
    ///        /* Generated by DVelop Work With Plus Pattern [Start] - Do not change */
    ///        /* Generated by DVelop Work With Plus Pattern [End] - Do not change */
    ///    Anything inside a Start..End region is regenerated on the next F9; telling the
    ///    developer to delete commented code there is telling them to fight the generator.
    ///    A second marker family ("//@ * ... GENERATED ... *" banner lines, Descartes-style)
    ///    is honoured defensively: it was reported by a prior agent but has NOT been verified
    ///    against a real object — if those banners exist, we skip; if they don't, the check
    ///    costs nothing.
    ///
    /// 2. PROSE IS NOT DEAD CODE. A 15-line change-history comment block must not fire.
    ///    The discriminator is the ratio of comment lines that LOOK like GeneXus code
    ///    (assignments, control flow, calls). Thresholds are parameters so the tests pin
    ///    them explicitly and a retune is a visible diff, not a silent behaviour change.
    /// </summary>
    internal static class CommentedCodeDetector
    {
        internal readonly struct Finding
        {
            public Finding(int startLine, int lineCount, int codeLikeLines)
            {
                StartLine = startLine;
                LineCount = lineCount;
                CodeLikeLines = codeLikeLines;
            }

            /// <summary>1-based line where the commented block starts.</summary>
            public int StartLine { get; }
            public int LineCount { get; }
            public int CodeLikeLines { get; }
        }

        // A comment line whose text reads like GeneXus code. Deliberately coarse: this decides
        // dead-code vs prose, not syntax validity. Anchored forms keep Spanish prose that merely
        // contains the word "si" or "para" from matching.
        private static readonly Regex[] CodeLikePatterns =
        {
            // &var = / += / -=  (assignment to a variable — the strongest signal)
            new Regex(@"^\s*&\w+\s*(=|\+=|-=)", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            // control flow / structural keywords at line start
            new Regex(@"^\s*(for\s+each\b|endfor\b|if\b|endif\b|else\b|do\s+while\b|do\s+case\b|case\b|endcase\b|enddo\b|new\b|endnew\b|sub\s+'|endsub\b|where\b|when\s+(none|duplicate)\b|commit\b|rollback\b|return\b|exit\b|parm\s*\()", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            // subroutine invocation: Do 'Name'
            new Regex(@"^\s*do\s+'", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            // method or procedure call: X.Y(...) or Name(...) alone on the line
            new Regex(@"\w+\s*\.\s*\w+\s*\(|^\s*\w+\s*\(.*\)\s*$", RegexOptions.Compiled)
        };

        // DVelop WorkWithPlus region markers — VERIFIED live (see class doc).
        private static readonly Regex WwpStartMarker = new Regex(@"generated\s+by\s+.*\[start\]", RegexOptions.IgnoreCase | RegexOptions.Compiled);
        private static readonly Regex WwpEndMarker = new Regex(@"generated\s+by\s+.*\[end\]", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        /// <summary>
        /// Scans ORIGINAL source (not comment-stripped — this detector lives off the comments
        /// that StripComments erases). Returns one finding per qualifying block.
        /// </summary>
        /// <param name="originalSource">The part's source as authored, comments included.</param>
        /// <param name="minLines">Blocks shorter than this never fire. Default 11 = "more than 10".</param>
        /// <param name="minCodeRatio">Share of block lines that must look like code. Below it, the block is prose.</param>
        internal static List<Finding> Detect(string originalSource, int minLines = 11, double minCodeRatio = 0.6)
        {
            var findings = new List<Finding>();
            if (string.IsNullOrEmpty(originalSource)) return findings;

            string[] lines = originalSource.Split('\n');

            bool inGeneratedRegion = false;   // DVelop [Start]..[End]
            bool inDescartesSkip = false;     // //@ *GENERATED* banner .. next //@ banner
            bool inBlockComment = false;      // /* .. */ spanning lines

            int runStart = -1, runLength = 0, runCodeLike = 0;

            void CloseRun()
            {
                if (runLength >= minLines && runCodeLike >= runLength * minCodeRatio)
                {
                    findings.Add(new Finding(runStart + 1, runLength, runCodeLike));
                }
                runStart = -1; runLength = 0; runCodeLike = 0;
            }

            for (int i = 0; i < lines.Length; i++)
            {
                string trimmed = lines[i].TrimEnd('\r').Trim();

                // ── Generated-region tracking (markers win over everything) ──
                if (WwpStartMarker.IsMatch(trimmed))
                {
                    CloseRun();
                    inGeneratedRegion = true;
                    continue;
                }
                if (WwpEndMarker.IsMatch(trimmed))
                {
                    CloseRun();
                    inGeneratedRegion = false;
                    continue;
                }
                if (trimmed.StartsWith("//@", StringComparison.Ordinal))
                {
                    // A banner line is never dead code and always breaks a run. A banner that
                    // says GENERATED opens the (unverified, defensive) Descartes skip; any other
                    // //@ banner closes it.
                    CloseRun();
                    inDescartesSkip = trimmed.IndexOf("GENERATED", StringComparison.OrdinalIgnoreCase) >= 0;
                    continue;
                }
                if (inGeneratedRegion || inDescartesSkip) continue;

                // ── Comment classification ──
                bool isCommentLine;
                string commentText = null;

                if (inBlockComment)
                {
                    isCommentLine = true;
                    int close = trimmed.IndexOf("*/", StringComparison.Ordinal);
                    if (close >= 0)
                    {
                        inBlockComment = false;
                        commentText = trimmed.Substring(0, close);
                    }
                    else
                    {
                        commentText = trimmed;
                    }
                }
                else if (trimmed.StartsWith("//", StringComparison.Ordinal))
                {
                    isCommentLine = true;
                    commentText = trimmed.Substring(2);
                }
                else if (trimmed.StartsWith("/*", StringComparison.Ordinal))
                {
                    isCommentLine = true;
                    commentText = trimmed.Substring(2);
                    int close = commentText.IndexOf("*/", StringComparison.Ordinal);
                    if (close >= 0) commentText = commentText.Substring(0, close);
                    else inBlockComment = true;
                }
                else
                {
                    isCommentLine = false;
                }

                if (isCommentLine)
                {
                    if (runLength == 0) runStart = i;
                    runLength++;
                    if (LooksLikeCode(commentText)) runCodeLike++;
                }
                else
                {
                    // Any non-comment line — code OR blank — breaks the run. Blank-breaks is the
                    // conservative choice: two separate 6-line relics with a gap read as two
                    // small blocks (neither fires), not one big one. Fewer false positives.
                    CloseRun();
                }
            }
            CloseRun();   // a block ending at EOF still counts

            return findings;
        }

        private static bool LooksLikeCode(string commentText)
        {
            if (string.IsNullOrWhiteSpace(commentText)) return false;
            foreach (var rx in CodeLikePatterns)
            {
                if (rx.IsMatch(commentText)) return true;
            }
            return false;
        }
    }
}
