using System;
using System.Linq;
using GxMcp.Worker.Helpers;
using Xunit;

namespace GxMcp.Worker.Tests
{
    /// <summary>
    /// Pins GX015's detection logic (dead commented-out code). Every threshold asserted here is
    /// normative — it comes from the team standard ("more than 10 lines") — so moving one is a
    /// deliberate standard change, not a refactor.
    /// </summary>
    public class CommentedCodeDetectorTests
    {
        private static string Lines(params string[] lines) => string.Join("\n", lines);

        /// <summary>Builds n commented-out assignment lines — unambiguous dead code.</summary>
        private static string[] DeadCodeLines(int n)
        {
            return Enumerable.Range(1, n).Select(i => "// &total" + i + " = &total" + i + " + 1").ToArray();
        }

        [Fact]
        public void Detect_ElevenCommentedCodeLines_Flagged()
        {
            // The threshold is "MORE than 10": eleven fires. StartLine must point at the block,
            // not at the file start — the issue is only actionable if it lands on the right line.
            var src = Lines(
                "&a = 1",
                "&b = 2");
            src += "\n" + Lines(DeadCodeLines(11)) + "\n&c = 3";

            var findings = CommentedCodeDetector.Detect(src);

            var f = Assert.Single(findings);
            Assert.Equal(3, f.StartLine);
            Assert.Equal(11, f.LineCount);
        }

        [Fact]
        public void Detect_TenLines_NotFlagged()
        {
            // The exact lower bound. If someone "tidies" the >= into a >, or shifts the default,
            // this goes red before any KB notices.
            var src = Lines(DeadCodeLines(10));

            Assert.Empty(CommentedCodeDetector.Detect(src));
        }

        [Fact]
        public void Detect_ProseCommentBlock_NotFlagged()
        {
            // Fifteen lines of Spanish change-history prose. This is the false positive that
            // would make developers ignore GX015 entirely: flagging documentation as dead code.
            // The code-ratio heuristic (0.6) is what keeps it out.
            var prose = Enumerable.Range(1, 15).Select(i =>
                "// 2026-0" + (i % 9 + 1) + "-15 wgarcia: se ajusta el calculo de intereses segun " +
                "lo solicitado por el area contable en el ticket " + (1000 + i)).ToArray();

            Assert.Empty(CommentedCodeDetector.Detect(Lines(prose)));
        }

        [Fact]
        public void Detect_WwpGeneratedRegion_Skipped()
        {
            // THE exclusion that makes GX015 shippable. Marker format verified live against
            // MatikaPayment_2702 (CompanyWW Events, 18 Start/End pairs): anything between
            // DVelop's [Start] and [End] markers is regenerated on the next F9 — flagging
            // commented code there tells the developer to fight the generator.
            var src = Lines(
                "/* Generated by DVelop Work With Plus Pattern [Start] - Do not change */")
                + "\n" + Lines(DeadCodeLines(20)) + "\n" + Lines(
                "/* Generated by DVelop Work With Plus Pattern [End] - Do not change */",
                "&x = 1");

            Assert.Empty(CommentedCodeDetector.Detect(src));
        }

        [Fact]
        public void Detect_AfterWwpEndMarker_DetectionResumes()
        {
            // The skip must END at [End] — a detector that never resumes after the first
            // generated region would silently disable GX015 for every WWP object.
            var src = Lines(
                "/* Generated by DVelop Work With Plus Pattern [Start] - Do not change */",
                "&generated = 1",
                "/* Generated by DVelop Work With Plus Pattern [End] - Do not change */")
                + "\n" + Lines(DeadCodeLines(12));

            var f = Assert.Single(CommentedCodeDetector.Detect(src));
            Assert.Equal(4, f.StartLine);
            Assert.Equal(12, f.LineCount);
        }

        [Fact]
        public void Detect_DescartesGeneratedBanner_OpensSkip_NextBannerCloses()
        {
            // Defensive support for the //@ banner family (Descartes-style). NOT verified
            // against a real object — reported by a prior agent's handoff. If those banners
            // exist this skips their region; if they never occur, the branch is inert.
            var src = Lines(
                "//@ * INTERNAL GENERATED EVENTS AND SUBROUTINES *")
                + "\n" + Lines(DeadCodeLines(15)) + "\n" + Lines(
                "//@ * END *")
                + "\n" + Lines(DeadCodeLines(11));

            var f = Assert.Single(CommentedCodeDetector.Detect(src));
            Assert.Equal(18, f.StartLine);   // only the block AFTER the closing banner fires
        }

        [Fact]
        public void Detect_BannerLineBreaksRun()
        {
            // A lone //@ line is never dead code and always breaks a run: 6 + banner + 6 is
            // two small blocks, not a 13-line one.
            var src = Lines(DeadCodeLines(6)) + "\n//@ separator\n" + Lines(DeadCodeLines(6));

            Assert.Empty(CommentedCodeDetector.Detect(src));
        }

        [Fact]
        public void Detect_CodeLineBreaksRun()
        {
            // Real code between two comment runs splits them. Summing across code would
            // manufacture a violation out of two legal 6-line relics.
            var src = Lines(DeadCodeLines(6)) + "\n&real = 1\n" + Lines(DeadCodeLines(6));

            Assert.Empty(CommentedCodeDetector.Detect(src));
        }

        [Fact]
        public void Detect_BlockCommentSpanningLines_CountsAsOneRun()
        {
            // Dead code fenced with /* ... */ across lines is the same smell as // per line.
            var inner = Enumerable.Range(1, 10).Select(i => "&monto" + i + " = &monto" + i + " * 2");
            var src = "/*\n" + string.Join("\n", inner) + "\n*/";   // 12 comment lines total

            var f = Assert.Single(CommentedCodeDetector.Detect(src));
            Assert.Equal(1, f.StartLine);
            Assert.Equal(12, f.LineCount);
        }

        [Fact]
        public void Detect_ThresholdsAreParameters_NotHardcoded()
        {
            // The tunables must stay tunable: a stricter team profile (e.g. 5 lines) is a
            // parameter change at the call site, not a fork of the detector.
            var src = Lines(DeadCodeLines(6));

            Assert.Empty(CommentedCodeDetector.Detect(src));                       // default 11
            Assert.Single(CommentedCodeDetector.Detect(src, minLines: 5));         // stricter profile
        }
    }
}
